/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eu.diversify.ffbpg.gui;

import eu.diversify.ffbpg.BPGraph;
import eu.diversify.ffbpg.Facade;
import eu.diversify.ffbpg.Simulation;
import eu.diversify.ffbpg.collections.SortedIntegerSet;
import eu.diversify.ffbpg.evolution.ApplicationLinksEvolutionScenario;
import eu.diversify.ffbpg.evolution.BalanceApplicationLinksEvolutionScenario;
import eu.diversify.ffbpg.evolution.BalancePlatformServicesEvolutionScenario;
import eu.diversify.ffbpg.evolution.EvolutionScenario;
import eu.diversify.ffbpg.evolution.InitializationEvolutionScenario;
import eu.diversify.ffbpg.evolution.PlatformServicesEvolutionScenario;
import eu.diversify.ffbpg.random.BinomialIntegerGenerator;
import eu.diversify.ffbpg.random.GaussianIntegerGenerator;
import eu.diversify.ffbpg.random.IntegerGenerator;
import eu.diversify.ffbpg.random.IntegerSetGenerator;
import eu.diversify.ffbpg.random.NegExpIntegerGenerator;
import eu.diversify.ffbpg.random.NegExpIntegerSetGenerator;
import eu.diversify.ffbpg.random.PoissonIntegerGenerator;
import eu.diversify.ffbpg.random.UniformIntegerGenerator;
import eu.diversify.ffbpg.random.UniformIntegerSetGenerator;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ProgressMonitor;
import sun.awt.image.PixelConverter;

/**
 *
 * @author ffl
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jComboBoxSimulAppScenario.setModel(new DefaultComboBoxModel(ApplicationLinksEvolutionScenario.getAllScenarioNames()));
        jComboBoxSimulPlatScenario.setModel(new DefaultComboBoxModel(PlatformServicesEvolutionScenario.getAllScenarioNames()));
        jComboBoxInitSimul.setModel(new DefaultComboBoxModel(InitializationEvolutionScenario.getAllScenarioNames()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAppSize = new javax.swing.ButtonGroup();
        buttonGroupSrvDist = new javax.swing.ButtonGroup();
        buttonGroupInitial = new javax.swing.ButtonGroup();
        buttonGroupLinking = new javax.swing.ButtonGroup();
        buttonGroupExtinction = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonSrvUniform = new javax.swing.JRadioButton();
        jRadioButtonSrvExp = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSrvLambda = new javax.swing.JTextField();
        jRadioButtonSrvComb = new javax.swing.JRadioButton();
        jTextFieldSrvURate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonAppUniform = new javax.swing.JRadioButton();
        jRadioButtonAppPoisson = new javax.swing.JRadioButton();
        jRadioButtonAppNormal = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAppLambda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAppMean = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAppVar = new javax.swing.JTextField();
        jRadioButtonAppBinomial = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAppN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAppP = new javax.swing.JTextField();
        jRadioButtonAppExponetial = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldAppExpLambda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldMinAppSize = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSimNApp = new javax.swing.JTextField();
        jTextFieldSimNSrv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldSimNPlats = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonInitExactMatch = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAppCapacity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSrvCapacity = new javax.swing.JTextField();
        jRadioButtonInitRandom = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButtonLinkSL = new javax.swing.JRadioButton();
        jRadioButtonLinkAL = new javax.swing.JRadioButton();
        jRadioButtonLinkAAllL = new javax.swing.JRadioButton();
        jCheckBoxNeighbourhood = new javax.swing.JCheckBox();
        jTextFieldNeighbourhood = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNGraphs = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBPGView = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldSimulSteps = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxSimulAppScenario = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNbExtinctions = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxSimulPlatScenario = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxInitSimul = new javax.swing.JComboBox();
        jCheckBoxBalanceLinks = new javax.swing.JCheckBox();
        jCheckBoxBalanceServices = new javax.swing.JCheckBox();
        jCheckBoxCalculateRobustness = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldExtinctionPercentage = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diversify Bi-Partite Graph Generator");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Services usage distribution"));

        buttonGroupSrvDist.add(jRadioButtonSrvUniform);
        jRadioButtonSrvUniform.setText("Uniform");

        buttonGroupSrvDist.add(jRadioButtonSrvExp);
        jRadioButtonSrvExp.setText("Exponetial");

        jLabel1.setText("lambda=");

        jTextFieldSrvLambda.setText("0.25");
        jTextFieldSrvLambda.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldSrvLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSrvLambdaActionPerformed(evt);
            }
        });

        buttonGroupSrvDist.add(jRadioButtonSrvComb);
        jRadioButtonSrvComb.setSelected(true);
        jRadioButtonSrvComb.setText("Combined");

        jTextFieldSrvURate.setText("0.005");
        jTextFieldSrvURate.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel4.setText("%");

        jLabel3.setText("uniform rate=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSrvUniform)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSrvComb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSrvURate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSrvExp)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSrvLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonSrvUniform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSrvExp)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSrvLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSrvComb)
                    .addComponent(jTextFieldSrvURate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Application size distribution"));

        buttonGroupAppSize.add(jRadioButtonAppUniform);
        jRadioButtonAppUniform.setText("Uniform");
        jRadioButtonAppUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAppUniformActionPerformed(evt);
            }
        });

        buttonGroupAppSize.add(jRadioButtonAppPoisson);
        jRadioButtonAppPoisson.setSelected(true);
        jRadioButtonAppPoisson.setText("Poisson");

        buttonGroupAppSize.add(jRadioButtonAppNormal);
        jRadioButtonAppNormal.setText("Normal");

        jLabel2.setText("lambda=");

        jTextFieldAppLambda.setText("6.0");
        jTextFieldAppLambda.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel5.setText("mean=");

        jTextFieldAppMean.setText("8.0");
        jTextFieldAppMean.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel6.setText("variance=");

        jTextFieldAppVar.setText("3.0");
        jTextFieldAppVar.setPreferredSize(new java.awt.Dimension(60, 20));

        buttonGroupAppSize.add(jRadioButtonAppBinomial);
        jRadioButtonAppBinomial.setText("Binomial (does not work)");
        jRadioButtonAppBinomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAppBinomialActionPerformed(evt);
            }
        });

        jLabel7.setText("n=");

        jTextFieldAppN.setText("1");
        jTextFieldAppN.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel8.setText("p=");

        jTextFieldAppP.setText("1.0");
        jTextFieldAppP.setPreferredSize(new java.awt.Dimension(60, 20));

        buttonGroupAppSize.add(jRadioButtonAppExponetial);
        jRadioButtonAppExponetial.setText("Exponential");
        jRadioButtonAppExponetial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAppExponetialActionPerformed(evt);
            }
        });

        jLabel20.setText("lambda=");

        jTextFieldAppExpLambda.setText("10");

        jLabel21.setText("Min app size=");

        jTextFieldMinAppSize.setText("1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("(used for all distributions)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonAppNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAppMean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAppExponetial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAppBinomial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAppN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAppExpLambda)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAppPoisson)
                            .addComponent(jRadioButtonAppUniform))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAppLambda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMinAppSize))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAppP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAppVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAppUniform)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldMinAppSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAppPoisson)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAppLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAppMean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAppVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonAppNormal))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAppN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldAppP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonAppBinomial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAppExponetial)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldAppExpLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("General simulation parameters"));

        jLabel9.setText("Number of applications");

        jTextFieldSimNApp.setText("300");
        jTextFieldSimNApp.setPreferredSize(new java.awt.Dimension(60, 20));

        jTextFieldSimNSrv.setText("50");
        jTextFieldSimNSrv.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldSimNSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSimNSrvActionPerformed(evt);
            }
        });

        jLabel10.setText("Number of services");

        jLabel17.setText("Number of platforms ");

        jTextFieldSimNPlats.setText("100");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSimNApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldSimNPlats)
                                .addGap(1, 1, 1))
                            .addComponent(jTextFieldSimNSrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSimNApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldSimNPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldSimNSrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Initial bi-partite graph"));

        buttonGroupInitial.add(jRadioButtonInitExactMatch);
        jRadioButtonInitExactMatch.setText("One platform / application - Exact services match");

        jLabel11.setText("Applications capacity:");

        jTextFieldAppCapacity.setText("100");

        jLabel13.setText("Servers capacity:");

        jTextFieldSrvCapacity.setText("18");

        buttonGroupInitial.add(jRadioButtonInitRandom);
        jRadioButtonInitRandom.setSelected(true);
        jRadioButtonInitRandom.setText("Random links to satisfy dependencies");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonInitExactMatch)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jRadioButtonInitRandom)
                            .addGap(104, 104, 104))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAppCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldSrvCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonInitExactMatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonInitRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldAppCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldSrvCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Applications \"linking startegy\""));

        buttonGroupLinking.add(jRadioButtonLinkSL);
        jRadioButtonLinkSL.setText("Link to a single platform");

        buttonGroupLinking.add(jRadioButtonLinkAL);
        jRadioButtonLinkAL.setSelected(true);
        jRadioButtonLinkAL.setText("Link to platforms offering at least one service");
        jRadioButtonLinkAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLinkALActionPerformed(evt);
            }
        });

        buttonGroupLinking.add(jRadioButtonLinkAAllL);
        jRadioButtonLinkAAllL.setText("Link to platforms offering all services");

        jCheckBoxNeighbourhood.setSelected(true);
        jCheckBoxNeighbourhood.setText("Restrict Neighbourhood to ");

        jTextFieldNeighbourhood.setText("25");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBoxNeighbourhood)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNeighbourhood))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLinkSL)
                            .addComponent(jRadioButtonLinkAL)
                            .addComponent(jRadioButtonLinkAAllL))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonLinkSL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLinkAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLinkAAllL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNeighbourhood)
                    .addComponent(jTextFieldNeighbourhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Bipartite graph generator"));

        jLabel12.setText("Number of graphs");

        jTextFieldNGraphs.setText("10");
        jTextFieldNGraphs.setPreferredSize(new java.awt.Dimension(60, 20));

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(bpgraphtable);
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        jButtonBPGView.setText("Explore...");
        jButtonBPGView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBPGViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNGraphs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBPGView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextFieldNGraphs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBPGView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        jLabel14.setText("Simulation steps: ");

        jTextFieldSimulSteps.setText("250");

        jLabel15.setText("Application Links Evolution: ");

        jButton2.setText("RUN FOR ONE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("# Extinctions:");

        jTextFieldNbExtinctions.setText("50");

        jLabel18.setText("Platform Services Evolution: ");

        jLabel19.setText("Initialization step(s): ");

        jCheckBoxBalanceLinks.setText("Remove unused links");

        jCheckBoxBalanceServices.setText("Remove services for saturated platforms");

        jCheckBoxCalculateRobustness.setSelected(true);
        jCheckBoxCalculateRobustness.setText("Calculate Robusness");

        jLabel23.setText("Extinction Percentage:");

        jTextFieldExtinctionPercentage.setText("100");

        jButton3.setText("RUN FOR ALL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextFieldNbExtinctions, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldExtinctionPercentage))
                            .addComponent(jTextFieldSimulSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSimulAppScenario, 0, 286, Short.MAX_VALUE)
                            .addComponent(jComboBoxSimulPlatScenario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxInitSimul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jCheckBoxBalanceLinks)
                    .addComponent(jCheckBoxBalanceServices)
                    .addComponent(jCheckBoxCalculateRobustness))
                .addGap(384, 384, 384))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSimulSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextFieldNbExtinctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jTextFieldExtinctionPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxCalculateRobustness)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxSimulAppScenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBalanceLinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxSimulPlatScenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBalanceServices))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxInitSimul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAppUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAppUniformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAppUniformActionPerformed

    private void jRadioButtonAppBinomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAppBinomialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAppBinomialActionPerformed

  // protected BPGraphListModel bpgraphlist = new BPGraphListModel();
   protected BPGraphTableModel bpgraphtable = new BPGraphTableModel();
   
   protected String generator_parameters = "";
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        final StringBuffer cfg = new StringBuffer();
      //  bpgraphlist.clear();
        bpgraphtable.clear();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        int n_run = Integer.parseInt(jTextFieldNGraphs.getText());
        
       
        
        final ProgressMonitor progressMonitor = new ProgressMonitor(this,
                                      "Generating Bi-Partite Graphs",
                                      "", 0, n_run);
       
        progressMonitor.setMillisToPopup(500);
        
        Thread queryThread = new Thread() {
      public void run() {
        int n_run = Integer.parseInt(jTextFieldNGraphs.getText());
               
        int n_app = Integer.parseInt(jTextFieldSimNApp.getText());
        int n_pla = Integer.parseInt(jTextFieldSimNPlats.getText());
        int n_srv = Integer.parseInt(jTextFieldSimNSrv.getText());
        
        int min_app_size = Integer.parseInt(jTextFieldMinAppSize.getText());
        
        int app_capacity = Integer.parseInt(jTextFieldAppCapacity.getText());
        int srv_capacity = Integer.parseInt(jTextFieldSrvCapacity.getText());
        
        cfg.append("# Number generated graphs\t"); cfg.append(n_run); cfg.append("\n");
        
        cfg.append("# Baseline Nodes\t"); cfg.append("One platform per application, exact service match"); cfg.append("\n");
        cfg.append("# Baseline Links\t"); cfg.append("One link between each application and its matching platform"); cfg.append("\n");
        
        cfg.append("# Number of applications\t"); cfg.append(n_app); cfg.append("\n");
        cfg.append("# Number of services\t"); cfg.append(n_srv); cfg.append("\n");
        
        cfg.append("# Application Capacity\t"); cfg.append(app_capacity); cfg.append("\n");
        cfg.append("# Servers Capacity\t"); cfg.append(srv_capacity); cfg.append("\n");
        
        cfg.append("# Minimum application size\t"); cfg.append(min_app_size); cfg.append("\n");
        
        cfg.append("# Dist. of application size\t");
        IntegerGenerator app_size_generator = null;
        if (jRadioButtonAppUniform.isSelected()) {
            app_size_generator = new UniformIntegerGenerator();
            cfg.append("Uniform"); cfg.append("\n");
        }
        else if (jRadioButtonAppNormal.isSelected()) {
            app_size_generator = new GaussianIntegerGenerator(Double.parseDouble(jTextFieldAppMean.getText()), Double.parseDouble(jTextFieldAppVar.getText()));
            cfg.append("Normal (mean="+jTextFieldAppMean.getText()+", var="+jTextFieldAppVar.getText()+")"); cfg.append("\n");
        }
        else if (jRadioButtonAppPoisson.isSelected()) {
            app_size_generator = new PoissonIntegerGenerator(Double.parseDouble(jTextFieldAppLambda.getText()));
            cfg.append("Poisson (lambda="+jTextFieldAppLambda.getText()+")"); cfg.append("\n");
        }
        else if (jRadioButtonAppBinomial.isSelected()) {
            app_size_generator = new BinomialIntegerGenerator(Integer.parseInt(jTextFieldAppN.getText()), Double.parseDouble(jTextFieldAppP.getText()));
            cfg.append("Binomial (N="+jTextFieldAppN.getText()+", P="+jTextFieldAppP.getText()+")"); cfg.append("\n");
        }
        else if (jRadioButtonAppExponetial.isSelected()) {
            app_size_generator = new NegExpIntegerGenerator(Double.parseDouble(jTextFieldAppExpLambda.getText()));
            cfg.append("Neg Exponential (Lambda="+jTextFieldAppExpLambda.getText()+")"); cfg.append("\n");
        }
        
        cfg.append("# Dist. of services usage\t");
        IntegerSetGenerator service_sets_generator = null;
        if (jRadioButtonSrvUniform.isSelected()) {
            service_sets_generator = new UniformIntegerSetGenerator();
            cfg.append("Uniform"); cfg.append("\n");
        }
        else if (jRadioButtonSrvExp.isSelected()) {
            service_sets_generator = new NegExpIntegerSetGenerator(Double.parseDouble(jTextFieldSrvLambda.getText()), 0);
            cfg.append("Exponetial (lambda="+jTextFieldSrvLambda.getText()+")"); cfg.append("\n");
        }
        else if (jRadioButtonSrvComb.isSelected()) {
            service_sets_generator = new NegExpIntegerSetGenerator(Double.parseDouble(jTextFieldSrvLambda.getText()), Double.parseDouble(jTextFieldSrvURate.getText()));
            cfg.append("Combined (lambda="+jTextFieldSrvLambda.getText()+", uniform factor="+jTextFieldSrvURate.getText()+")"); cfg.append("\n");
        }
        
        BPGraph g;
        boolean _cfg = true;
        
        for(int i=0; i<n_run; i++) {
            System.out.println("Run #" + i);
            final int progress = i+1;
            java.awt.EventQueue.invokeLater(new Runnable() {    
                public void run() {
                   progressMonitor.setProgress(progress);
               }
                });
           
            
            if (jRadioButtonInitExactMatch.isSelected()) {
                    g = new BPGraph(n_srv);
                SortedIntegerSet[] ssets = g.getRandomGenerator().createRandomServiceSets(g.getServices(), n_app, app_size_generator, service_sets_generator, min_app_size);
                g.createGraphWithOnePlatformPerApplicationAndSingleLink(ssets, app_capacity, srv_capacity);

                int neighbourhood = g.getPlatforms().size();
                if (jCheckBoxNeighbourhood.isSelected())
                    neighbourhood = Integer.parseInt(jTextFieldNeighbourhood.getText());
                if (jRadioButtonLinkAL.isSelected()) {
                    g.addLinksFromApplicationsToPlatformsProvidingAtLeastOneSrv(neighbourhood);
                    if (_cfg) {cfg.append("# Additional links to neighbouring platform offering at least 1 required service"); cfg.append("\n");}
                }
                else if (jRadioButtonLinkAAllL.isSelected()) {
                   g.addLinksFromApplicationsToPlatformsProvidingAllSrv(neighbourhood);
                   if (_cfg) {cfg.append("# Additional links to neighbouring platform all required service"); cfg.append("\n");}
                }
                if (_cfg) {cfg.append("# Neighbourhood Size\t"); cfg.append(neighbourhood); cfg.append("\n");}
               // bpgraphlist.add(g);
                bpgraphtable.add(g);
            }
            else if (jRadioButtonInitRandom.isSelected()) {
                if (_cfg) {
                    cfg.append("# Number of platforms\t"); cfg.append(n_pla); cfg.append("\n");
                    cfg.append("# Adding a random set of links in order to satisfy dependencies of applications\n");
                    cfg.append("# Pruning applications for which are not alive\n");
                }
                g = Facade.createRandomBPGraph(n_app, n_pla, n_srv, app_size_generator, service_sets_generator, app_capacity, srv_capacity, min_app_size);
                bpgraphtable.add(g);
            }
            
            
            
            
            
            
            _cfg = false;
        }
        generator_parameters = cfg.toString();
      }
      
    };
    queryThread.start();
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBPGViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBPGViewActionPerformed
        
        if (bpgraphtable.getData().size() == 0) return;
        int row = jTable1.getSelectedRow();
        if (row < 0) row = 0;
        BPGraphFrame f = new BPGraphFrame();
        f.setVisible(true);
        f.setBPGraphCollection((List<BPGraph>)bpgraphtable.getData().clone(), row, generator_parameters);
        
     
    }//GEN-LAST:event_jButtonBPGViewActionPerformed

    private void jTextFieldSrvLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSrvLambdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSrvLambdaActionPerformed

    private void jRadioButtonLinkALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLinkALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLinkALActionPerformed

    private void jTextFieldSimNSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSimNSrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSimNSrvActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
                final int sim_steps = Integer.parseInt(jTextFieldSimulSteps.getText());

                if (bpgraphtable.getData().size() == 0) return;
                int row = jTable1.getSelectedRow();
                if (row < 0) row = 0;
                BPGraph initial = bpgraphtable.getData().get(row);
                
                final Simulation s = create_simulation_for_model(initial);
                
                
                final ProgressMonitor progressMonitor = new ProgressMonitor(this,
                                      "Simulating Bi-Partite Graph Evolution",
                                      "", 0, sim_steps);
       
                progressMonitor.setMillisToPopup(500);

                Thread queryThread = new Thread() {
                    public void run() {
                        
                        for (int i=0; i<sim_steps; i++) {
                            BPGraph g = s.run_step();
                            if (jCheckBoxCalculateRobustness.isSelected()) {
                                int r = s.computeRobustnessExtinctionSequences(g);
                                System.out.println("Robustness at step " + i + ":" + r);
                            }
                            final int progress = i+1;
                            java.awt.EventQueue.invokeLater(new Runnable() {    
                                public void run() {
                                   progressMonitor.setProgress(progress);
                               }});
                            if (progressMonitor.isCanceled()) break;
                        }
                        
                        if (!progressMonitor.isCanceled())
                        java.awt.EventQueue.invokeLater(new Runnable() {    
                                public void run() {
                                   BPGraphFrame f = new BPGraphFrame();
                                    f.setVisible(true);    
                                    String log = generator_parameters + "\n\n" + s.getSim_parameters();
                                    f.setSimulation(s);
                               }});
                        
                    }
                };
                queryThread.start();
            
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    protected Simulation create_simulation_for_model(BPGraph initial) {
       
            Simulation result = new Simulation();
            result.setInitial(initial);
            
            result.setApplicationLinksEvolutionScenario(ApplicationLinksEvolutionScenario.getScenarioByName(jComboBoxSimulAppScenario.getSelectedItem().toString()));
            result.setPlatformServicesEvolutionScenario(PlatformServicesEvolutionScenario.getScenarioByName(jComboBoxSimulPlatScenario.getSelectedItem().toString()));
            result.setInitializationEvolutionScenario(InitializationEvolutionScenario.getScenarioByName(jComboBoxInitSimul.getSelectedItem().toString()));
            if (jCheckBoxBalanceServices.isSelected()) result.setBalancePlatformServicesEvolutionScenario(new BalancePlatformServicesEvolutionScenario());
            if (jCheckBoxBalanceLinks.isSelected()) result.setBalanceApplicationLinksEvolutionScenario(new BalanceApplicationLinksEvolutionScenario());
            
            result.setExtinction_sequence_runs(Integer.parseInt(jTextFieldNbExtinctions.getText()));
            result.setExtinction_sequence_percentage(Integer.parseInt(jTextFieldExtinctionPercentage.getText()));

            result.run_init();
            
            return result;
            
    }
    
    
    private void jRadioButtonAppExponetialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAppExponetialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAppExponetialActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        SimulationsFrame f = new SimulationsFrame();
        
        // Create simulations for all initial models
        for (BPGraph g : bpgraphtable.getData()) {
            Simulation s = create_simulation_for_model(g);
            f.addSimulation(s);
        }
        
        f.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        
        
       
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAppSize;
    private javax.swing.ButtonGroup buttonGroupExtinction;
    private javax.swing.ButtonGroup buttonGroupInitial;
    private javax.swing.ButtonGroup buttonGroupLinking;
    private javax.swing.ButtonGroup buttonGroupSrvDist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBPGView;
    private javax.swing.JCheckBox jCheckBoxBalanceLinks;
    private javax.swing.JCheckBox jCheckBoxBalanceServices;
    private javax.swing.JCheckBox jCheckBoxCalculateRobustness;
    private javax.swing.JCheckBox jCheckBoxNeighbourhood;
    private javax.swing.JComboBox jComboBoxInitSimul;
    private javax.swing.JComboBox jComboBoxSimulAppScenario;
    private javax.swing.JComboBox jComboBoxSimulPlatScenario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonAppBinomial;
    private javax.swing.JRadioButton jRadioButtonAppExponetial;
    private javax.swing.JRadioButton jRadioButtonAppNormal;
    private javax.swing.JRadioButton jRadioButtonAppPoisson;
    private javax.swing.JRadioButton jRadioButtonAppUniform;
    private javax.swing.JRadioButton jRadioButtonInitExactMatch;
    private javax.swing.JRadioButton jRadioButtonInitRandom;
    private javax.swing.JRadioButton jRadioButtonLinkAAllL;
    private javax.swing.JRadioButton jRadioButtonLinkAL;
    private javax.swing.JRadioButton jRadioButtonLinkSL;
    private javax.swing.JRadioButton jRadioButtonSrvComb;
    private javax.swing.JRadioButton jRadioButtonSrvExp;
    private javax.swing.JRadioButton jRadioButtonSrvUniform;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAppCapacity;
    private javax.swing.JTextField jTextFieldAppExpLambda;
    private javax.swing.JTextField jTextFieldAppLambda;
    private javax.swing.JTextField jTextFieldAppMean;
    private javax.swing.JTextField jTextFieldAppN;
    private javax.swing.JTextField jTextFieldAppP;
    private javax.swing.JTextField jTextFieldAppVar;
    private javax.swing.JTextField jTextFieldExtinctionPercentage;
    private javax.swing.JTextField jTextFieldMinAppSize;
    private javax.swing.JTextField jTextFieldNGraphs;
    private javax.swing.JTextField jTextFieldNbExtinctions;
    private javax.swing.JTextField jTextFieldNeighbourhood;
    private javax.swing.JTextField jTextFieldSimNApp;
    private javax.swing.JTextField jTextFieldSimNPlats;
    private javax.swing.JTextField jTextFieldSimNSrv;
    private javax.swing.JTextField jTextFieldSimulSteps;
    private javax.swing.JTextField jTextFieldSrvCapacity;
    private javax.swing.JTextField jTextFieldSrvLambda;
    private javax.swing.JTextField jTextFieldSrvURate;
    // End of variables declaration//GEN-END:variables
}
