# Extinction sequence for 50 applications  and 50 platforms.
plot \
"testBPGraphGaussianMultiLinksAvg.dat" using 2 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 3 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 4 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 5 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 6 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 7 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 8 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 9 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 10 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 11 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 12 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 13 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 14 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 15 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 16 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 17 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 18 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 19 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 20 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 21 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 22 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 23 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 24 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 25 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 26 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 27 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 28 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 29 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 30 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 31 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 32 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 33 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 34 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 35 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 36 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 37 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 38 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 39 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 40 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 41 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 42 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 43 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 44 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 45 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 46 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 47 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 48 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 49 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 50 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 51 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 52 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 53 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 54 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 55 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 56 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 57 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 58 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 59 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 60 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 61 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 62 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 63 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 64 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 65 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 66 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 67 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 68 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 69 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 70 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 71 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 72 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 73 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 74 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 75 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 76 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 77 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 78 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 79 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 80 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 81 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 82 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 83 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 84 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 85 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 86 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 87 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 88 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 89 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 90 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 91 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 92 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 93 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 94 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 95 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 96 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 97 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 98 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 99 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 100 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 101 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 102 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 103 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 104 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 105 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 106 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 107 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 108 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 109 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 110 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 111 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 112 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 113 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 114 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 115 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 116 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 117 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 118 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 119 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 120 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 121 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 122 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 123 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 124 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 125 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 126 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 127 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 128 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 129 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 130 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 131 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 132 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 133 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 134 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 135 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 136 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 137 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 138 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 139 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 140 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 141 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 142 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 143 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 144 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 145 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 146 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 147 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 148 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 149 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 150 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 151 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 152 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 153 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 154 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 155 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 156 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 157 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 158 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 159 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 160 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 161 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 162 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 163 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 164 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 165 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 166 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 167 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 168 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 169 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 170 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 171 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 172 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 173 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 174 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 175 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 176 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 177 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 178 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 179 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 180 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 181 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 182 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 183 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 184 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 185 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 186 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 187 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 188 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 189 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 190 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 191 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 192 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 193 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 194 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 195 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 196 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 197 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 198 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 199 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 200 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 201 notitle with lines lc rgb 'grey', \
"testBPGraphGaussianMultiLinksAvg.dat" using 202 title 'Average' with lines lw 2 lc rgb 'red', \
"testBPGraphGaussianMultiLinksAvg.dat" using 203 title 'Reference' with line lt 'dashed' lw 2 lc rgb 'black'
